name: chessmate
description: "Graduation Project - Smart Chessboard"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.10.8 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Icons
  cupertino_icons: ^1.0.8

  # Firebase Core and Auth
  firebase_core: ^3.15.2
  firebase_auth: ^5.1.1
  google_sign_in: ^6.2.1

  # Firestore (for User Profiles)
  cloud_firestore: ^5.0.2

  # Firebase Realtime Database (CRITICAL for Raspberry Pi Sync)
  firebase_database: ^11.3.1

  # Bluetooth (CRITICAL for Local Board Connection)
  flutter_blue_plus: ^1.31.20
  permission_handler: ^11.3.1

  # Logic & UI
  url_launcher: ^6.3.0
  chess: ^0.8.1
  provider: ^6.1.2
  shared_preferences: ^2.3.2
  audioplayers: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
